[package]
name = "mini_decompiler"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "1.4", optional = true }
iced-x86 = { version = "1.21", default-features = false, features = ["std","decoder","instr_info","nasm"] }
lancelot-flirt = "0.10.0"
object = "0.32"
ureq = { version = "2", default-features = false, features = ["json", "native-tls"] }
native-tls = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"

[build-dependencies]
object = "0.32"

[[bin]]
name = "mini_decompiler"
path = "src/main.rs"

[lib]
name = "mini_decompiler"
path = "src/lib.rs"

[[bin]]
name = "dpp-gui"
path = "src/bin/gui.rs"
required-features = ["gui"]

[[bin]]
name = "ai_test"
path = "src/bin/ai_test.rs"

[features]
gui = ["fltk"]
