[package]
name = "mini_decompiler"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "1.4", optional = true }
iced-x86 = { version = "1.21", default-features = false, features = ["std","decoder","instr_info","nasm"] }
object = "0.32"

[[bin]]
name = "mini_decompiler"
path = "src/main.rs"

[lib]
name = "mini_decompiler"
path = "src/lib.rs"

[[bin]]
name = "dpp-gui"
path = "src/bin/gui.rs"
required-features = ["gui"]

[features]
gui = ["fltk"]
